swagger: "2.0"
info:
  title: ""
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /objects:
    post:
      tags:
      - objects
      summary: create objects
      description: Insert a new object
      operationId: objects#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ObjectsCreateRequestBody'
          required:
          - name
          - key
          - id
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ObjectsCreateResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ObjectsCreateInternalServerErrorResponseBody'
      schemes:
      - http
  /objects/{objectID}:
    get:
      tags:
      - objects
      summary: show objects
      description: Get object by id
      operationId: objects#show
      parameters:
      - name: objectID
        in: path
        description: Object ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ObjectsShowResponseBodyFull'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ObjectsShowBadRequestResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ObjectsShowNotFoundResponseBody'
      schemes:
      - http
definitions:
  ObjectsCreateInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: create_InternalServerError_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ObjectsCreateRequestBody:
    title: ObjectsCreateRequestBody
    type: object
    properties:
      enabled:
        type: boolean
        description: Object is enabled or not
        default: true
        example: false
      id:
        type: string
        description: A string to identify the Object.
        example: u
        minLength: 1
      key:
        type: string
        description: Object's Key
        example: Et qui harum et.
      logo:
        type: string
        description: Object's Logo
        example: Ea porro temporibus voluptatem nemo magnam delectus.
      name:
        type: string
        description: Object's Name
        example: Provident et ut porro.
    example:
      enabled: false
      id: "2"
      key: Libero adipisci.
      logo: A quae atque ut possimus.
      name: Dicta ut placeat labore quas cumque.
    required:
    - name
    - key
    - id
  ObjectsCreateResponseBody:
    title: 'Mediatype identifier: application/vnd.object.media+json; view=default'
    type: object
    properties:
      createdDate:
        type: string
        description: 'Date when the Object was created default: now.'
        example: "2001-07-28T08:14:47Z"
        format: date-time
      enabled:
        type: boolean
        description: Object is enabled or not
        default: true
        example: false
      id:
        type: string
        description: Unique object ID
        example: i4g
        minLength: 1
      key:
        type: string
        description: Key of Object
        example: Quis dicta magni vel et.
      logo:
        type: string
        description: Logo of Object
        example: Ea et.
      name:
        type: string
        description: Name of Object
        example: Ratione accusamus.
      updatedDate:
        type: string
        description: 'Date when the Object was updated default: now.'
        example: "1971-01-15T01:25:59Z"
        format: date-time
    description: CreateResponseBody result type (default view)
    example:
      createdDate: "1979-12-18T08:48:33Z"
      enabled: true
      id: ztt
      key: Harum hic similique dolore fugiat ut corrupti.
      logo: Suscipit non et velit enim rem.
      name: Porro iste dolorem alias molestias.
      updatedDate: "2005-07-03T20:01:42Z"
    required:
    - id
    - key
    - name
    - enabled
  ObjectsShowBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: show_BadRequest_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ObjectsShowNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: show_NotFound_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ObjectsShowResponseBodyFull:
    title: 'Mediatype identifier: application/vnd.object.media+json; view=full'
    type: object
    properties:
      createdDate:
        type: string
        description: 'Date when the Object was created default: now.'
        example: "1975-05-24T08:53:39Z"
        format: date-time
      enabled:
        type: boolean
        description: Object is enabled or not
        default: true
        example: false
      id:
        type: string
        description: Unique object ID
        example: mp6
        minLength: 1
      key:
        type: string
        description: Key of Object
        example: Reprehenderit inventore.
      logo:
        type: string
        description: Logo of Object
        example: Doloremque consectetur consequuntur.
      name:
        type: string
        description: Name of Object
        example: Quibusdam dicta adipisci consectetur.
      updatedDate:
        type: string
        description: 'Date when the Object was updated default: now.'
        example: "2003-05-08T13:42:26Z"
        format: date-time
    description: ShowResponseBody result type (full view) (default view)
    example:
      createdDate: "2012-02-22T19:38:07Z"
      enabled: false
      id: w
      key: Reprehenderit consequatur deserunt cupiditate officia.
      logo: Consequatur quia a ea ut.
      name: Rerum vel corrupti et.
      updatedDate: "1988-03-18T16:29:11Z"
    required:
    - id
    - key
    - name
    - enabled
